# Form implementation generated from reading ui file '账户登录.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # 设置主窗口基本属性
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(450, 500)  # 原宽度 527，减少 40
        # 设置窗口初始位置，将界面左边往回缩短，这里示例设置 x 坐标为 100
        MainWindow.move(100, 0)
        
        # 创建中心部件
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 创建标题标签
        self.biao_qian1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.biao_qian1.setGeometry(QtCore.QRect(95, 30, 201, 41))  # 左移 45px 近似居中
        self.biao_qian1.setStyleSheet("QLabel {\n"
"    font-family: \"微软雅黑\";  /* 指定字体 */\n"
"    font-weight: bold;\n"
"    font-size: 18px;\n"
" qproperty-alignment: AlignCenter;"
"}")
        self.biao_qian1.setObjectName("biao_qian1")

        # 创建用户名输入框
        self.wen_ben1 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.wen_ben1.setGeometry(QtCore.QRect(115, 110, 221, 41))  # 左移 65px 近似居中
        self.wen_ben1.setStyleSheet(" background-color: rgb(255, 255, 255);  \n"
"QLineEdit, QTextEdit {\n"
"    border: 1px solid #cccccc;  /* 边框颜色 */\n"
"    border-radius: 5px;         /* 圆角半径（可调整） */\n"
"    padding: 5px;               /* 内边距 */\n"
"    color: #666666;             /* 灰色字体 */\n"
"    font-size: 14px;            /* 字体大小（可选） */\n"
"}")
        self.wen_ben1.setObjectName("wen_ben1")

        # 创建密码输入框
        self.wen_ben1_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.wen_ben1_2.setGeometry(QtCore.QRect(115, 210, 221, 41))  # 左移 65px 近似居中
        self.wen_ben1_2.setStyleSheet(" background-color: rgb(255, 255, 255);  \n"
"QLineEdit, QTextEdit {\n"
"    border: 1px solid #cccccc;  /* 边框颜色 */\n"
"    border-radius: 5px;         /* 圆角半径（可调整） */\n"
"    padding: 5px;               /* 内边距 */\n"
"    color: #666666;             /* 灰色字体 */\n"
"    font-size: 14px;            /* 字体大小（可选） */\n"
"}")
        self.wen_ben1_2.setObjectName("wen_ben1_2")

        # 创建登录按钮
        self.zhu_ce = QtWidgets.QPushButton(parent=self.centralwidget)
        self.zhu_ce.setGeometry(QtCore.QRect(115, 300, 221, 41))  # 左移 65px 近似居中
        self.zhu_ce.setStyleSheet("/* 蓝色按钮样式 */\n"
"QPushButton {\n"
"   background-color: rgb(74, 126, 246);\n"
"    border-radius: 2.5px;           /* 圆角大小（可调整） */\n"
"    padding: 8px 16px;            /* 内边距 */\n"
"    color: white;                 /* 白色文字 */\n"
"    font-weight: bold;            /* 加粗文字 */\n"
"}\n"
"\n"
"/* 按下时的深蓝色效果 */\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 88, 173);    /* 更深的蓝色 */\n"
"    border: 2px solid #004a87;    /* 更深的边框色 */\n"
"}\n"
"")
        self.zhu_ce.setObjectName("zhu_ce")

        # 创建注册链接按钮
        self.deng_lu = QtWidgets.QCommandLinkButton(parent=self.centralwidget)
        self.deng_lu.setGeometry(QtCore.QRect(135, 400, 181, 31))  # 左移 65px 近似居中
        self.deng_lu.setStyleSheet("font-family: \"微软雅黑\";  /* 指定字体 */\n"
"font-size: 12px;")
        icon = QtGui.QIcon.fromTheme("accessories-calculator")
        self.deng_lu.setIcon(icon)
        self.deng_lu.setObjectName("deng_lu")
        
        # 设置中心部件和菜单栏
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        
        # 设置状态栏
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # 翻译UI文本
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.biao_qian1.setText(_translate("MainWindow", "            用户登录"))
        self.wen_ben1.setPlainText(_translate("MainWindow", "请输入用户名"))
        self.wen_ben1_2.setPlainText(_translate("MainWindow", "请输入密码"))
        self.zhu_ce.setText(_translate("MainWindow", "立即登录"))
        self.deng_lu.setText(_translate("MainWindow", "            注册新账号"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())